import "./globals.css";
import { Playfair_Display, Lobster_Two } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Define main font
const playfair = Playfair_Display({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-playfair",
});
const lobster = Lobster_Two({
  weight: ["700"],
  subsets: ["latin"],
  variable: "--font-lobster",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${playfair.variable} ${lobster.variable}`} lang="en">
      <body className="max-w-full font-playfair">{children}</body>
    </html>
  );
}
